### ISSUE TITLE
Load XGBoost tree from json byte array in memory

### ISSUE THREAD

**Issue by jcronq** [Elvenson/xgboost-go#9]
There's currently a dependency on hard disk to which the XGBoost JSON has been saved.  I have a use case to run this library on a device that may or may not have a hard disk, and need to be able to load the model from memory instead.

Proposed fix: 
Create a new function that unmarshal's the object from a byte array.
Pull out the common components of the two load functions into a new function.

**Comment by jcronq** [comment]
Created PR for fixing this issue: https://github.com/Elvenson/xgboost-go/pull/10

**Comment by Elvenson** [comment]
Thanks you for your suggestion! I have merged your MR so I will close this issue.
